# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exchange_rates_pb2 as exchange__rates__pb2


class ExchangeRatesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExchangeRates = channel.unary_unary(
                '/ExchangeRates/GetExchangeRates',
                request_serializer=exchange__rates__pb2.ExchangeRatesRequest.SerializeToString,
                response_deserializer=exchange__rates__pb2.ExchangeRatesResponse.FromString,
                )
        self.GetExchangeRatesStream = channel.unary_stream(
                '/ExchangeRates/GetExchangeRatesStream',
                request_serializer=exchange__rates__pb2.Empty.SerializeToString,
                response_deserializer=exchange__rates__pb2.ExchangeRate.FromString,
                )


class ExchangeRatesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExchangeRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExchangeRatesStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeRatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExchangeRates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangeRates,
                    request_deserializer=exchange__rates__pb2.ExchangeRatesRequest.FromString,
                    response_serializer=exchange__rates__pb2.ExchangeRatesResponse.SerializeToString,
            ),
            'GetExchangeRatesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetExchangeRatesStream,
                    request_deserializer=exchange__rates__pb2.Empty.FromString,
                    response_serializer=exchange__rates__pb2.ExchangeRate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExchangeRates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExchangeRates(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExchangeRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExchangeRates/GetExchangeRates',
            exchange__rates__pb2.ExchangeRatesRequest.SerializeToString,
            exchange__rates__pb2.ExchangeRatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExchangeRatesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ExchangeRates/GetExchangeRatesStream',
            exchange__rates__pb2.Empty.SerializeToString,
            exchange__rates__pb2.ExchangeRate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
