# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streamer.proto',
  package='GrpcStreaming',
  syntax='proto3',
  serialized_options=b'\252\002\023GrpcStreaming.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0estreamer.proto\x12\rGrpcStreaming\".\n\rStreamMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2a\n\rStreamService\x12P\n\x0eStartStreaming\x12\x1c.GrpcStreaming.StreamMessage\x1a\x1c.GrpcStreaming.StreamMessage(\x01\x30\x01\x42\x16\xaa\x02\x13GrpcStreaming.Protob\x06proto3'
)




_STREAMMESSAGE = _descriptor.Descriptor(
  name='StreamMessage',
  full_name='GrpcStreaming.StreamMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GrpcStreaming.StreamMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='GrpcStreaming.StreamMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['StreamMessage'] = _STREAMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamMessage = _reflection.GeneratedProtocolMessageType('StreamMessage', (_message.Message,), {
  'DESCRIPTOR' : _STREAMMESSAGE,
  '__module__' : 'streamer_pb2'
  # @@protoc_insertion_point(class_scope:GrpcStreaming.StreamMessage)
  })
_sym_db.RegisterMessage(StreamMessage)


DESCRIPTOR._options = None

_STREAMSERVICE = _descriptor.ServiceDescriptor(
  name='StreamService',
  full_name='GrpcStreaming.StreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=81,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartStreaming',
    full_name='GrpcStreaming.StreamService.StartStreaming',
    index=0,
    containing_service=None,
    input_type=_STREAMMESSAGE,
    output_type=_STREAMMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMSERVICE)

DESCRIPTOR.services_by_name['StreamService'] = _STREAMSERVICE

# @@protoc_insertion_point(module_scope)
